<a href="https://colab.research.google.com/github/Muneebshah1192/flyrank-ml-internship/blob/main/work/notebooks/w07_action_playbook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!git clone https://github.com/Muneebshah1192/flyrank-ml-internship.git
%cd flyrank-ml-internship
!git status

Cloning into 'flyrank-ml-internship'...
remote: Enumerating objects: 196, done.
remote: Counting objects: 100% (196/196), done.
remote: Compressing objects: 100% (165/165), done.
remote: Total 196 (delta 81), reused 76 (delta 13), pack-reused 0 (from 0)
Receiving objects: 100% (196/196), 2.03 MiB | 14.57 MiB/s, done.
Resolving deltas: 100% (81/81), done.
/content/flyrank-ml-internship
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean

In [2]:
!find work -maxdepth 3 -type f | sort

work/capstone_report_template.md
work/notebooks/capstone.ipynb
work/notebooks/w01_research_question.ipynb
work/notebooks/w02_ml_task_framing.ipynb
work/notebooks/w03_data_contract.ipynb
work/notebooks/w03_feature_leakage_check.ipynb
work/notebooks/w04_baseline_score.ipynb
work/notebooks/w04_signal_audit.ipynb
work/notebooks/w05_model.ipynb
work/notebooks/w06_validation_audit.ipynb
work/notebooks/w07_action_playbook.ipynb
work/README.md

In [3]:
!cat skills/README.md

# Skills — the router

This folder is a small library of **skills**: focused instruction files your AI assistant loads
one at a time. One skill per task keeps the assistant sharp — its context window is small, and
filling it with everything makes it worse at the one thing you need.

**How to use it (repo-reading agents — Claude Code, Cursor, Codex):** they find this file
automatically via `AGENTS.md` / `CLAUDE.md`. Just tell your assistant which task you're doing.

**Using a chat-only assistant (ChatGPT / Gemini in a browser)?** Open the skill file on GitHub,
copy its whole content, and paste it into your chat before asking for help. That's it.

## The table — find your task, load ONE skill

| Your task | Load this skill | Also load for data work |
|---|---|---|
| Any task — how to work with your assistant at all | `directing-your-ai-assistant/SKILL.md` | — |
| Pick a lane, frame your question (ML-02, ML-03) | `framing-ml-problems/SKILL.md` | `flyrank/flyrank-data/SKILL.md` |
| Write + verify the data contract (ML-04) | `writing-data-contracts/SKILL.md` | `flyrank/flyrank-data/SKILL.md` |
| Query the big warehouse without downloading it (ML-04/05, capstone) | `querying-big-datasets/SKILL.md` | `flyrank/flyrank-data/SKILL.md` |
| EDA + signal tests with verdicts (ML-06) | `auditing-signals/SKILL.md` | `flyrank/flyrank-data/SKILL.md` |
| Build the rule baseline + ranked queue (ML-07) | `building-baselines/SKILL.md` | `flyrank/flyrank-data/SKILL.md` |
| Train and compare the model (ML-08) | `training-honest-models/SKILL.md` | `flyrank/flyrank-data/SKILL.md` |
| Hunt leakage; validate honestly (ML-05, ML-09) | `hunting-leakage-and-validating/SKILL.md` | `flyrank/flyrank-data/SKILL.md` |
| Write claims that hold (ML-09, ML-10, the paper) | `writing-honest-claims/SKILL.md` | — |
| Write the research paper (ML-11, W7) | `writing-research-papers/SKILL.md` | — |
| Deploy the paper as a page (ML-11) | `deploying-static-pages/SKILL.md` | — |
| Understand FlyRank + the problem (background) | `flyrank/flyrank-context/SKILL.md` | — |

## Reuse this on your next project

Every skill outside `flyrank/` is **general** — take this whole folder to any future project.
Delete `skills/flyrank/` and the flyrank column above, and everything else still works.

In [4]:
!find skills -maxdepth 3 -type f | sort

skills/auditing-signals/SKILL.md
skills/building-baselines/SKILL.md
skills/deploying-static-pages/SKILL.md
skills/directing-your-ai-assistant/SKILL.md
skills/flyrank/flyrank-context/SKILL.md
skills/flyrank/flyrank-data/SKILL.md
skills/framing-ml-problems/SKILL.md
skills/hunting-leakage-and-validating/SKILL.md
skills/querying-big-datasets/SKILL.md
skills/README.md
skills/training-honest-models/SKILL.md
skills/writing-data-contracts/SKILL.md
skills/writing-honest-claims/SKILL.md
skills/writing-research-papers/SKILL.md

In [5]:
!find work -type f | sort

work/capstone_report_template.md
work/notebooks/capstone.ipynb
work/notebooks/w01_research_question.ipynb
work/notebooks/w02_ml_task_framing.ipynb
work/notebooks/w03_data_contract.ipynb
work/notebooks/w03_feature_leakage_check.ipynb
work/notebooks/w04_baseline_score.ipynb
work/notebooks/w04_signal_audit.ipynb
work/notebooks/w05_model.ipynb
work/notebooks/w06_validation_audit.ipynb
work/notebooks/w07_action_playbook.ipynb
work/README.md

In [6]:
!ls -lh work/notebooks/

total 1.2M
-rw-r--r-- 1 root root 303K Aug 22 14:22 capstone.ipynb
-rw-r--r-- 1 root root  11K Aug 22 14:22 w01_research_question.ipynb
-rw-r--r-- 1 root root 6.0K Aug 22 14:22 w02_ml_task_framing.ipynb
-rw-r--r-- 1 root root 345K Aug 22 14:22 w03_data_contract.ipynb
-rw-r--r-- 1 root root 2.4K Aug 22 14:22 w03_feature_leakage_check.ipynb
-rw-r--r-- 1 root root 222K Aug 22 14:22 w04_baseline_score.ipynb
-rw-r--r-- 1 root root 2.3K Aug 22 14:22 w04_signal_audit.ipynb
-rw-r--r-- 1 root root 150K Aug 22 14:22 w05_model.ipynb
-rw-r--r-- 1 root root 128K Aug 22 14:22 w06_validation_audit.ipynb
-rw-r--r-- 1 root root 2.6K Aug 22 14:22 w07_action_playbook.ipynb

In [7]:
import json

path = "work/notebooks/w07_action_playbook.ipynb"

with open(path, "r", encoding="utf-8") as f:
    nb = json.load(f)

for i, cell in enumerate(nb["cells"]):
    print(f"\n--- CELL {i} [{cell['cell_type']}] ---")
    print("".join(cell["source"])[:3000])

--- CELL 0 [markdown] ---
# ML-10 — Content Action Playbook

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

--- CELL 1 [markdown] ---
## 1. Ranked actions + reason codes

*The queue: what to do first, and why, in words a human trusts.*

--- CELL 2 [code] ---


--- CELL 3 [markdown] ---
## 2. Intended use and limits

*Who uses this, for what — and where it stops being valid.*

--- CELL 4 [code] ---


--- CELL 5 [markdown] ---
## 3. Human review + the no-go list

*What a person must check before acting. What should never be automated.*

--- CELL 6 [code] ---


--- CELL 7 [markdown] ---
## 4. Monitoring / retrain triggers

*What would tell you the recommendations went stale?*

--- CELL 8 [code] ---


--- CELL 9 [markdown] ---
## 5. Exports for the paper

*Write the queue (and any figures you want to reuse) to work/outputs/ — your paper builds on these files.*

--- CELL 10 [code] ---


--- CELL 11 [markdown] ---
## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.

In [8]:
!find . -iname "*.csv" -o -iname "*.parquet" -o -iname "*.json"

./data/raw/content_refresh_anonymized.csv
./outputs/refresh_queue_sample.csv

In [10]:
import pandas as pd

data_path = "./data/raw/content_refresh_anonymized.csv"

df = pd.read_csv(data_path)

print("Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

Shape: (30000, 44)

Columns:
['content_id', 'client_id', 'search_volume', 'competition', 'competition_level', 'cpc', 'content_type', 'main_intent', 'word_count', 'char_count', 'provider_used', 'model_used', 'impressions_90d', 'clicks_90d', 'pageviews_90d', 'sessions_90d', 'users_90d', 'engaged_sessions_90d', 'ai_sessions_90d', 'scroll_events_90d', 'days_with_impressions', 'days_with_sessions', 'impressions_last_30d', 'clicks_last_30d', 'sessions_last_30d', 'impressions_prev_30d', 'clicks_prev_30d', 'sessions_prev_30d', 'content_age_days', 'age_tier', 'age_tier_order', 'days_since_last_update', 'freshness_tier', 'word_count_tier', 'char_count_tier', 'ctr', 'avg_position', 'engagement_rate', 'scroll_rate', 'ai_traffic_pct', 'impression_tier', 'position_tier', 'trend_direction', 'trend_pct']

In [11]:
display(df.head())

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,char_count_tier,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct
0,content_304f48230142,client_f369cb89fc,10.0,0.67,HIGH,2.05,keyword article,transactional,3221.0,20457.0,...,15000-25000,0.76,10.6,5.88,4.55,0.0,good,striking,down,-41.4
1,content_a1fb4e703a9e,client_4e07408562,90.0,0.01,LOW,0.05,keyword article,informational,2481.0,15562.0,...,15000-25000,0.05,20.3,0.00,10.00,0.0,good,page_3_5,down,-57.7
2,content_9aa793d4d895,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,3515.0,23643.0,...,15000-25000,0.09,36.5,0.00,28.57,0.0,good,page_3_5,down,-60.9
3,content_331d6c4de07b,client_19581e27de,10.0,0.00,LOW,0.00,keyword article,commercial,NaN,NaN,...,NaN,0.49,6.2,1.28,3.45,0.0,good,page_1,stable,-13.8
4,content_d99b7a2d90ca,client_3fdba35f04,0.0,0.00,LOW,0.00,keyword article,informational,2803.0,17469.0,...,15000-25000,0.13,44.0,0.00,24.29,0.0,good,page_3_5,down,-34.7

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 44 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   content_id              30000 non-null  object
 1   client_id               30000 non-null  object
 2   search_volume           27532 non-null  float64
 3   competition             27532 non-null  float64
 4   competition_level       27390 non-null  object
 5   cpc                     27532 non-null  float64
 6   content_type            30000 non-null  object
 7   main_intent             27626 non-null  object
 8   word_count              22301 non-null  float64
 9   char_count              22301 non-null  float64
 10  provider_used           8562 non-null   object
 11  model_used              24267 non-null  object
 12  impressions_90d         30000 non-null  int64
 13  clicks_90d              30000 non-null  int64
 14  pageviews_90d           30000 non-null  int64
 15  sessions_90d            30000 non-null  int64
 16  users_90d               30000 non-null  int64
 17  engaged_sessions_90d    30000 non-null  int64
 18  ai_sessions_90d         30000 non-null  int64
 19  scroll_events_90d       30000 non-null  int64
 20  days_with_impressions   30000 non-null  int64
 21  days_with_sessions      30000 non-null  int64
 22  impressions_last_30d    30000 non-null  int64
 23  clicks_last_30d         30000 non-null  int64
 24  sessions_last_30d       30000 non-null  int64
 25  impressions_prev_30d    30000 non-null  int64
 26  clicks_prev_30d         30000 non-null  int64
 27  sessions_prev_30d       30000 non-null  int64
 28  content_age_days        30000 non-null  int64
 29  age_tier                30000 non-null  object
 30  age_tier_order          30000 non-null  int64
 31  days_since_last_update  30000 non-null  int64
 32  freshness_tier          30000 non-null  object
 33  word_count_tier         22301 non-null  object
 34  char_count_tier         22301 non-null  object
 35  ctr                     30000 non-null  float64
 36  avg_position            30000 non-null  float64
 37  engagement_rate         30000 non-null  float64
 38  scroll_rate             29875 non-null  float64
 39  ai_traffic_pct          30000 non-null  float64
 40  impression_tier         30000 non-null  object
 41  position_tier           30000 non-null  object
 42  trend_direction         30000 non-null  object
 43  trend_pct               26612 non-null  float64
dtypes: float64(11), int64(19), object(14)
memory usage: 10.1+ MB

In [13]:
queue_path = "./outputs/refresh_queue_sample.csv"

queue = pd.read_csv(queue_path)

print("Queue shape:", queue.shape)
print("\nQueue columns:")
print(queue.columns.tolist())

display(queue.head(10))

Queue shape: (200, 28)

Queue columns:
['final_rank', 'content_id', 'client_id', 'final_refresh_score', 'best_model_name', 'best_model_probability', 'baseline_refresh_score', 'confidence', 'suggested_action', 'final_reason_codes', 'is_declining_label', 'impressions_90d', 'clicks_90d', 'sessions_90d', 'avg_position', 'ctr', 'content_age_days', 'days_since_last_update', 'word_count', 'trend_direction', 'competition_level', 'content_type', 'main_intent', 'age_tier', 'freshness_tier', 'word_count_tier', 'impression_tier', 'position_tier']

,final_rank,content_id,client_id,final_refresh_score,best_model_name,best_model_probability,baseline_refresh_score,confidence,suggested_action,final_reason_codes,...,word_count,trend_direction,competition_level,content_type,main_intent,age_tier,freshness_tier,word_count_tier,impression_tier,position_tier
0,1,content_1f080331fa2b,client_3fdba35f04,81.636697,random_forest,0.782079,0.844481,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|low...,...,1404.0,down,MEDIUM,keyword article,informational,91-180,91-180,1000-2000,good,page_1
1,2,content_6aa43079fb0c,client_3fdba35f04,81.447656,random_forest,0.788105,0.825477,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,...,1457.0,down,LOW,keyword article,informational,91-180,91-180,1000-2000,good,page_1
2,3,content_d6570c51c9bd,client_3fdba35f04,81.430346,random_forest,0.847372,0.695884,medium,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,...,1362.0,down,MEDIUM,keyword article,informational,91-180,91-180,1000-2000,moderate,striking
3,4,content_72e800a9c214,client_3fdba35f04,81.034960,random_forest,0.774371,0.842545,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,...,1371.0,down,MEDIUM,keyword article,commercial,91-180,91-180,1000-2000,good,page_1
4,5,content_e04eb9549989,client_3fdba35f04,80.873188,random_forest,0.814805,0.749468,medium,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,...,1408.0,down,LOW,keyword article,informational,91-180,91-180,1000-2000,good,page_1
5,6,content_b69288c5e701,client_3fdba35f04,80.754770,random_forest,0.795713,0.787358,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,...,1370.0,down,LOW,keyword article,informational,91-180,91-180,1000-2000,good,page_1
6,7,content_9b6df29f7889,client_3fdba35f04,80.632923,random_forest,0.846245,0.673530,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,...,1415.0,down,MEDIUM,keyword article,commercial,91-180,91-180,1000-2000,moderate,page_1
7,8,content_bb6ebb5ec8c8,client_3fdba35f04,80.371236,random_forest,0.834638,0.690665,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,...,1381.0,down,LOW,keyword article,informational,91-180,91-180,1000-2000,moderate,striking
8,9,content_4d76cdb3387b,client_3fdba35f04,80.362748,random_forest,0.843092,0.671993,medium,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,...,1554.0,down,HIGH,keyword article,commercial,91-180,91-180,1000-2000,moderate,top_3
9,10,content_b4f35d640b1c,client_3fdba35f04,80.321757,random_forest,0.843803,0.669168,medium,refresh,declining_with_demand|model_decline_risk|visib...,...,1389.0,down,HIGH,keyword article,commercial,91-180,91-180,1000-2000,good,page_3_5

In [14]:
# ML-10 Section 1: Ranked actions + reason codes

import pandas as pd
import numpy as np
from IPython.display import display

# Load the existing validated refresh queue from the previous ML work.
queue_path = "./outputs/refresh_queue_sample.csv"
queue = pd.read_csv(queue_path)

# Keep the ranked queue ordered by the existing model-derived rank.
queue = queue.sort_values("final_rank").reset_index(drop=True)

# Convert reason-code strings into readable labels.
reason_labels = {
    "declining_with_demand": "Demand is declining",
    "low_ctr_visible_page": "Low CTR despite search visibility",
    "model_decline_risk": "Model indicates decline risk",
    "moderate_ctr_visible_page": "Moderate CTR with search visibility",
    "low_impressions": "Low search visibility",
    "stale_content": "Content appears stale",
    "old_content": "Older content",
    "low_engagement": "Low engagement",
    "position_opportunity": "Ranking position offers improvement opportunity",
}

def explain_reason_codes(value):
    if pd.isna(value):
        return "No reason code recorded"

    codes = str(value).split("|")
    readable = [reason_labels.get(code, code.replace("_", " ")) for code in codes]
    return "; ".join(readable)

queue["reason_explanation"] = queue["final_reason_codes"].apply(explain_reason_codes)

# Create the human-readable action queue.
action_queue = queue[
    [
        "final_rank",
        "content_id",
        "client_id",
        "final_refresh_score",
        "confidence",
        "suggested_action",
        "final_reason_codes",
        "reason_explanation",
        "trend_direction",
        "ctr",
        "avg_position",
        "content_age_days",
        "days_since_last_update",
        "content_type",
        "main_intent",
        "freshness_tier",
        "impression_tier",
        "position_tier",
    ]
].copy()

action_queue = action_queue.rename(
    columns={
        "final_rank": "rank",
        "final_refresh_score": "priority_score",
        "suggested_action": "recommended_action",
        "final_reason_codes": "reason_codes",
    }
)

# Display the first 20 ranked recommendations.
print("Top 20 content actions:")
display(action_queue.head(20))

# Basic summary of the recommendations.
print("\nAction distribution:")
display(action_queue["recommended_action"].value_counts(dropna=False))

print("\nConfidence distribution:")
display(action_queue["confidence"].value_counts(dropna=False))

print("\nReason-code examples:")
display(
    action_queue[
        ["rank", "content_id", "recommended_action", "reason_codes", "reason_explanation"]
    ].head(10)
)

Top 20 content actions:

,rank,content_id,client_id,priority_score,confidence,recommended_action,reason_codes,reason_explanation,trend_direction,ctr,avg_position,content_age_days,days_since_last_update,content_type,main_intent,freshness_tier,impression_tier,position_tier
0,1,content_1f080331fa2b,client_3fdba35f04,81.636697,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|low...,Demand is declining; Low CTR despite search vi...,down,0.05,6.8,165,104,keyword article,informational,91-180,good,page_1
1,2,content_6aa43079fb0c,client_3fdba35f04,81.447656,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,Demand is declining; Low CTR despite search vi...,down,0.07,3.8,139,104,keyword article,informational,91-180,good,page_1
2,3,content_d6570c51c9bd,client_3fdba35f04,81.430346,medium,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,Demand is declining; Low CTR despite search vi...,down,0.00,10.1,165,104,keyword article,informational,91-180,moderate,striking
3,4,content_72e800a9c214,client_3fdba35f04,81.034960,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,Demand is declining; Low CTR despite search vi...,down,0.12,8.2,139,104,keyword article,commercial,91-180,good,page_1
4,5,content_e04eb9549989,client_3fdba35f04,80.873188,medium,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,Demand is declining; Low CTR despite search vi...,down,0.09,3.6,131,104,keyword article,informational,91-180,good,page_1
5,6,content_b69288c5e701,client_3fdba35f04,80.754770,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,Demand is declining; Low CTR despite search vi...,down,0.07,6.4,144,104,keyword article,informational,91-180,good,page_1
6,7,content_9b6df29f7889,client_3fdba35f04,80.632923,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,Demand is declining; Low CTR despite search vi...,down,0.12,3.1,139,104,keyword article,commercial,91-180,moderate,page_1
7,8,content_bb6ebb5ec8c8,client_3fdba35f04,80.371236,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,Demand is declining; Low CTR despite search vi...,down,0.00,12.8,144,104,keyword article,informational,91-180,moderate,striking
8,9,content_4d76cdb3387b,client_3fdba35f04,80.362748,medium,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,Demand is declining; Low CTR despite search vi...,down,0.13,2.7,131,104,keyword article,commercial,91-180,moderate,top_3
9,10,content_b4f35d640b1c,client_3fdba35f04,80.321757,medium,refresh,declining_with_demand|model_decline_risk|visib...,Demand is declining; Model indicates decline r...,down,0.05,27.5,131,104,keyword article,commercial,91-180,good,page_3_5
10,11,content_ba6f9dfcbca1,client_3fdba35f04,80.282275,medium,refresh,declining_with_demand|model_decline_risk|visib...,Demand is declining; Model indicates decline r...,down,0.09,20.1,124,104,keyword article,transactional,91-180,good,page_3_5
11,12,content_1b51115391a3,client_3fdba35f04,80.134145,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,Demand is declining; Low CTR despite search vi...,down,0.00,9.5,155,104,keyword article,informational,91-180,good,page_1
12,13,content_e76ac7fed711,client_3fdba35f04,80.062755,medium,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,Demand is declining; Low CTR despite search vi...,down,0.05,5.8,139,104,keyword article,commercial,91-180,moderate,page_1
13,14,content_b1d593faf9c6,client_3fdba35f04,79.957743,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|low...,Demand is declining; Low CTR despite search vi...,down,0.00,8.3,148,104,keyword article,informational,91-180,moderate,page_1
14,15,content_20ddbdfbbd90,client_3fdba35f04,79.878200,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|low...,Demand is declining; Low CTR despite search vi...,down,0.14,11.2,148,104,keyword article,informational,91-180,good,striking
15,16,content_73b70737ee63,client_3fdba35f04,79.875242,medium,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,Demand is declining; Low CTR despite search vi...,down,0.19,2.8,139,104,keyword article,transactional,91-180,moderate,top_3
16,17,content_81e59177b59a,client_19581e27de,79.601277,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,Demand is declining; Low CTR despite search vi...,down,0.03,5.6,139,104,keyword article,informational,91-180,good,page_1
17,18,content_91fefd1726b3,client_3fdba35f04,79.562384,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,Demand is declining; Low CTR despite search vi...,down,0.07,18.7,148,104,keyword article,informational,91-180,moderate,striking
18,19,content_aa76dcfed6e7,client_3fdba35f04,79.557090,high,refresh_and_review_engagement,declining_with_demand|low_engagement_visible_p...,Demand is declining; low engagement visible pa...,down,0.04,21.1,165,104,keyword article,transactional,91-180,moderate,page_3_5
19,20,content_03475a5923fe,client_3fdba35f04,79.539037,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,Demand is declining; Low CTR despite search vi...,down,0.12,6.2,139,104,keyword article,commercial,91-180,moderate,page_1

Action distribution:

recommended_action
refresh_and_review_ctr           130
refresh                           35
refresh_and_review_engagement     35
Name: count, dtype: int64

Confidence distribution:

confidence
high      161
medium     39
Name: count, dtype: int64

Reason-code examples:

,rank,content_id,recommended_action,reason_codes,reason_explanation
0,1,content_1f080331fa2b,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|low...,Demand is declining; Low CTR despite search vi...
1,2,content_6aa43079fb0c,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,Demand is declining; Low CTR despite search vi...
2,3,content_d6570c51c9bd,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,Demand is declining; Low CTR despite search vi...
3,4,content_72e800a9c214,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,Demand is declining; Low CTR despite search vi...
4,5,content_e04eb9549989,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,Demand is declining; Low CTR despite search vi...
5,6,content_b69288c5e701,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,Demand is declining; Low CTR despite search vi...
6,7,content_9b6df29f7889,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,Demand is declining; Low CTR despite search vi...
7,8,content_bb6ebb5ec8c8,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,Demand is declining; Low CTR despite search vi...
8,9,content_4d76cdb3387b,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,Demand is declining; Low CTR despite search vi...
9,10,content_b4f35d640b1c,refresh,declining_with_demand|model_decline_risk|visib...,Demand is declining; Model indicates decline r...


ML-10 — Content Action Playbook
This skeleton is yours to fill. Work the sections in order — each one has a one-line hint. Simple words, honest numbers.

Working with an AI assistant? Tell it to read skills/README.md first and load the one skill this assignment names on its card.

1. Ranked actions + reason codes
The queue: what to do first, and why, in words a human trusts.



     
2. Intended use and limits
Who uses this, for what — and where it stops being valid.



     
3. Human review + the no-go list
What a person must check before acting. What should never be automated.



     
4. Monitoring / retrain triggers
What would tell you the recommendations went stale?



     
5. Exports for the paper
Write the queue (and any figures you want to reuse) to work/outputs/ — your paper builds on these files.



     
Self-check
Before you submit, confirm each line honestly:

Every section above is filled — markdown thinking AND the code that backs it
The notebook runs top to bottom with no errors (Runtime → Run all)
No client names, URLs, or private queries anywhere
My claims use careful words: observed, measured, directional, decision-support
Committed to my repo under work/notebooks/ — then submit your repo URL on the card. Done.

In [15]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import display

# Paths
data_path = "data/raw/content_refresh_anonymized.csv"
queue_path = "outputs/refresh_queue_sample.csv"

# Load the source dataset
df = pd.read_csv(data_path)

# Load the previously generated/validated refresh queue
queue = pd.read_csv(queue_path)

print("Source dataset shape:", df.shape)
print("Refresh queue shape:", queue.shape)

display(queue.head())

Source dataset shape: (30000, 44)
Refresh queue shape: (200, 28)

,final_rank,content_id,client_id,final_refresh_score,best_model_name,best_model_probability,baseline_refresh_score,confidence,suggested_action,final_reason_codes,...,word_count,trend_direction,competition_level,content_type,main_intent,age_tier,freshness_tier,word_count_tier,impression_tier,position_tier
0,1,content_1f080331fa2b,client_3fdba35f04,81.636697,random_forest,0.782079,0.844481,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|low...,...,1404.0,down,MEDIUM,keyword article,informational,91-180,91-180,1000-2000,good,page_1
1,2,content_6aa43079fb0c,client_3fdba35f04,81.447656,random_forest,0.788105,0.825477,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,...,1457.0,down,LOW,keyword article,informational,91-180,91-180,1000-2000,good,page_1
2,3,content_d6570c51c9bd,client_3fdba35f04,81.430346,random_forest,0.847372,0.695884,medium,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,...,1362.0,down,MEDIUM,keyword article,informational,91-180,91-180,1000-2000,moderate,striking
3,4,content_72e800a9c214,client_3fdba35f04,81.034960,random_forest,0.774371,0.842545,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,...,1371.0,down,MEDIUM,keyword article,commercial,91-180,91-180,1000-2000,good,page_1
4,5,content_e04eb9549989,client_3fdba35f04,80.873188,random_forest,0.814805,0.749468,medium,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,...,1408.0,down,LOW,keyword article,informational,91-180,91-180,1000-2000,good,page_1

# 1. Ranked actions + reason codes

The action queue uses the previously generated refresh output. Items are ordered using the existing `final_rank` and `final_refresh_score`.

Each recommendation contains a suggested action, confidence level, and reason codes. These signals explain why an item was prioritized.

The recommendations are intended for human review. A high score does not guarantee that changing a page will improve traffic, rankings, or conversions.

In [16]:
# Keep the existing model-derived ranking.
queue = queue.sort_values("final_rank").reset_index(drop=True)

# Translate common reason codes into plain-language explanations.
reason_labels = {
    "declining_with_demand": "Demand is declining",
    "low_ctr_visible_page": "Low CTR despite search visibility",
    "model_decline_risk": "Model indicates decline risk",
    "moderate_ctr_visible_page": "Moderate CTR with search visibility",
    "low_impressions": "Low search visibility",
    "stale_content": "Content appears stale",
    "old_content": "Older content",
    "low_engagement": "Low engagement",
    "position_opportunity": "Ranking position offers improvement opportunity",
}

def explain_reason_codes(value):
    if pd.isna(value):
        return "No reason code recorded"

    codes = str(value).split("|")

    explanations = [
        reason_labels.get(
            code,
            code.replace("_", " ")
        )
        for code in codes
    ]

    return "; ".join(explanations)

queue["reason_explanation"] = queue["final_reason_codes"].apply(
    explain_reason_codes
)

# Create the final human-readable action queue.
action_queue = queue[
    [
        "final_rank",
        "content_id",
        "client_id",
        "final_refresh_score",
        "confidence",
        "suggested_action",
        "final_reason_codes",
        "reason_explanation",
        "trend_direction",
        "ctr",
        "avg_position",
        "content_age_days",
        "days_since_last_update",
        "content_type",
        "main_intent",
        "freshness_tier",
        "impression_tier",
        "position_tier",
    ]
].copy()

action_queue = action_queue.rename(
    columns={
        "final_rank": "rank",
        "final_refresh_score": "priority_score",
        "suggested_action": "recommended_action",
        "final_reason_codes": "reason_codes",
    }
)

print("Top 20 ranked actions:")
display(action_queue.head(20))

Top 20 ranked actions:

,rank,content_id,client_id,priority_score,confidence,recommended_action,reason_codes,reason_explanation,trend_direction,ctr,avg_position,content_age_days,days_since_last_update,content_type,main_intent,freshness_tier,impression_tier,position_tier
0,1,content_1f080331fa2b,client_3fdba35f04,81.636697,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|low...,Demand is declining; Low CTR despite search vi...,down,0.05,6.8,165,104,keyword article,informational,91-180,good,page_1
1,2,content_6aa43079fb0c,client_3fdba35f04,81.447656,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,Demand is declining; Low CTR despite search vi...,down,0.07,3.8,139,104,keyword article,informational,91-180,good,page_1
2,3,content_d6570c51c9bd,client_3fdba35f04,81.430346,medium,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,Demand is declining; Low CTR despite search vi...,down,0.00,10.1,165,104,keyword article,informational,91-180,moderate,striking
3,4,content_72e800a9c214,client_3fdba35f04,81.034960,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,Demand is declining; Low CTR despite search vi...,down,0.12,8.2,139,104,keyword article,commercial,91-180,good,page_1
4,5,content_e04eb9549989,client_3fdba35f04,80.873188,medium,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,Demand is declining; Low CTR despite search vi...,down,0.09,3.6,131,104,keyword article,informational,91-180,good,page_1
5,6,content_b69288c5e701,client_3fdba35f04,80.754770,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,Demand is declining; Low CTR despite search vi...,down,0.07,6.4,144,104,keyword article,informational,91-180,good,page_1
6,7,content_9b6df29f7889,client_3fdba35f04,80.632923,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,Demand is declining; Low CTR despite search vi...,down,0.12,3.1,139,104,keyword article,commercial,91-180,moderate,page_1
7,8,content_bb6ebb5ec8c8,client_3fdba35f04,80.371236,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,Demand is declining; Low CTR despite search vi...,down,0.00,12.8,144,104,keyword article,informational,91-180,moderate,striking
8,9,content_4d76cdb3387b,client_3fdba35f04,80.362748,medium,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,Demand is declining; Low CTR despite search vi...,down,0.13,2.7,131,104,keyword article,commercial,91-180,moderate,top_3
9,10,content_b4f35d640b1c,client_3fdba35f04,80.321757,medium,refresh,declining_with_demand|model_decline_risk|visib...,Demand is declining; Model indicates decline r...,down,0.05,27.5,131,104,keyword article,commercial,91-180,good,page_3_5
10,11,content_ba6f9dfcbca1,client_3fdba35f04,80.282275,medium,refresh,declining_with_demand|model_decline_risk|visib...,Demand is declining; Model indicates decline r...,down,0.09,20.1,124,104,keyword article,transactional,91-180,good,page_3_5
11,12,content_1b51115391a3,client_3fdba35f04,80.134145,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,Demand is declining; Low CTR despite search vi...,down,0.00,9.5,155,104,keyword article,informational,91-180,good,page_1
12,13,content_e76ac7fed711,client_3fdba35f04,80.062755,medium,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,Demand is declining; Low CTR despite search vi...,down,0.05,5.8,139,104,keyword article,commercial,91-180,moderate,page_1
13,14,content_b1d593faf9c6,client_3fdba35f04,79.957743,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|low...,Demand is declining; Low CTR despite search vi...,down,0.00,8.3,148,104,keyword article,informational,91-180,moderate,page_1
14,15,content_20ddbdfbbd90,client_3fdba35f04,79.878200,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|low...,Demand is declining; Low CTR despite search vi...,down,0.14,11.2,148,104,keyword article,informational,91-180,good,striking
15,16,content_73b70737ee63,client_3fdba35f04,79.875242,medium,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,Demand is declining; Low CTR despite search vi...,down,0.19,2.8,139,104,keyword article,transactional,91-180,moderate,top_3
16,17,content_81e59177b59a,client_19581e27de,79.601277,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,Demand is declining; Low CTR despite search vi...,down,0.03,5.6,139,104,keyword article,informational,91-180,good,page_1
17,18,content_91fefd1726b3,client_3fdba35f04,79.562384,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,Demand is declining; Low CTR despite search vi...,down,0.07,18.7,148,104,keyword article,informational,91-180,moderate,striking
18,19,content_aa76dcfed6e7,client_3fdba35f04,79.557090,high,refresh_and_review_engagement,declining_with_demand|low_engagement_visible_p...,Demand is declining; low engagement visible pa...,down,0.04,21.1,165,104,keyword article,transactional,91-180,moderate,page_3_5
19,20,content_03475a5923fe,client_3fdba35f04,79.539037,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,Demand is declining; Low CTR despite search vi...,down,0.12,6.2,139,104,keyword article,commercial,91-180,moderate,page_1

In [17]:
print("Recommended action distribution:")
display(
    action_queue["recommended_action"]
    .value_counts(dropna=False)
    .to_frame("count")
)

print("\nConfidence distribution:")
display(
    action_queue["confidence"]
    .value_counts(dropna=False)
    .to_frame("count")
)

print("\nReason-code examples:")
display(
    action_queue[
        [
            "rank",
            "content_id",
            "recommended_action",
            "reason_codes",
            "reason_explanation",
        ]
    ].head(10)
)

Recommended action distribution:

                               count
recommended_action
refresh_and_review_ctr           130
refresh                           35
refresh_and_review_engagement     35

Confidence distribution:

            count
confidence
high          161
medium         39

Reason-code examples:

,rank,content_id,recommended_action,reason_codes,reason_explanation
0,1,content_1f080331fa2b,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|low...,Demand is declining; Low CTR despite search vi...
1,2,content_6aa43079fb0c,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,Demand is declining; Low CTR despite search vi...
2,3,content_d6570c51c9bd,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,Demand is declining; Low CTR despite search vi...
3,4,content_72e800a9c214,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,Demand is declining; Low CTR despite search vi...
4,5,content_e04eb9549989,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,Demand is declining; Low CTR despite search vi...
5,6,content_b69288c5e701,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,Demand is declining; Low CTR despite search vi...
6,7,content_9b6df29f7889,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,Demand is declining; Low CTR despite search vi...
7,8,content_bb6ebb5ec8c8,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,Demand is declining; Low CTR despite search vi...
8,9,content_4d76cdb3387b,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,Demand is declining; Low CTR despite search vi...
9,10,content_b4f35d640b1c,refresh,declining_with_demand|model_decline_risk|visib...,Demand is declining; Model indicates decline r...

In [18]:
required_columns = [
    "rank",
    "content_id",
    "priority_score",
    "confidence",
    "recommended_action",
    "reason_codes",
]

missing_columns = [
    column for column in required_columns
    if column not in action_queue.columns
]

if missing_columns:
    raise ValueError(
        f"Missing required columns: {missing_columns}"
    )

if len(action_queue) == 0:
    raise ValueError("Action queue is empty.")

if not action_queue["rank"].is_monotonic_increasing:
    raise ValueError("Action queue is not correctly ranked.")

print("Section 1 validation passed.")
print("Number of recommendations:", len(action_queue))
print(
    "Rank range:",
    action_queue["rank"].min(),
    "to",
    action_queue["rank"].max()
)

Section 1 validation passed.
Number of recommendations: 200
Rank range: 1 to 200

In [19]:
required_columns = [
    "rank",
    "content_id",
    "priority_score",
    "confidence",
    "recommended_action",
    "reason_codes",
]

missing_columns = [
    column for column in required_columns
    if column not in action_queue.columns
]

if missing_columns:
    raise ValueError(
        f"Missing required columns: {missing_columns}"
    )

if len(action_queue) == 0:
    raise ValueError("Action queue is empty.")

if not action_queue["rank"].is_monotonic_increasing:
    raise ValueError("Action queue is not correctly ranked.")

print("Section 1 validation passed.")
print("Number of recommendations:", len(action_queue))
print(
    "Rank range:",
    action_queue["rank"].min(),
    "to",
    action_queue["rank"].max()
)

Section 1 validation passed.
Number of recommendations: 200
Rank range: 1 to 200

# ML-10 — Content Action Playbook

This notebook converts a validated content-refresh scoring output into a practical,
human-reviewed content action playbook.

The output is intended for decision-support: it ranks content that may deserve
refresh or review based on observed content, traffic, freshness, trend, and model
signals.

The recommendations are directional rather than production decisions. A human
should review the underlying page and business context before taking action.

## 1. Ranked actions + reason codes

The ranked queue contains 200 recommendations ordered by the final refresh score.

The highest-ranked records receive the strongest priority because they combine
multiple observed signals associated with possible content refresh opportunities.

Reason codes make the recommendations easier to interpret. Examples include
declining demand, low CTR on visible pages, model-indicated decline risk, and
low engagement on visible pages.

The queue is used as a prioritization aid rather than as an automatic publishing
decision.

In [20]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os

# Load the previously generated refresh queue
queue_path = "outputs/refresh_queue_sample.csv"

queue = pd.read_csv(queue_path)

print("Queue shape:", queue.shape)
print("Queue columns:")
print(queue.columns.tolist())

display(queue.head(10))

Queue shape: (200, 28)
Queue columns:
['final_rank', 'content_id', 'client_id', 'final_refresh_score', 'best_model_name', 'best_model_probability', 'baseline_refresh_score', 'confidence', 'suggested_action', 'final_reason_codes', 'is_declining_label', 'impressions_90d', 'clicks_90d', 'sessions_90d', 'avg_position', 'ctr', 'content_age_days', 'days_since_last_update', 'word_count', 'trend_direction', 'competition_level', 'content_type', 'main_intent', 'age_tier', 'freshness_tier', 'word_count_tier', 'impression_tier', 'position_tier']

,final_rank,content_id,client_id,final_refresh_score,best_model_name,best_model_probability,baseline_refresh_score,confidence,suggested_action,final_reason_codes,...,word_count,trend_direction,competition_level,content_type,main_intent,age_tier,freshness_tier,word_count_tier,impression_tier,position_tier
0,1,content_1f080331fa2b,client_3fdba35f04,81.636697,random_forest,0.782079,0.844481,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|low...,...,1404.0,down,MEDIUM,keyword article,informational,91-180,91-180,1000-2000,good,page_1
1,2,content_6aa43079fb0c,client_3fdba35f04,81.447656,random_forest,0.788105,0.825477,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,...,1457.0,down,LOW,keyword article,informational,91-180,91-180,1000-2000,good,page_1
2,3,content_d6570c51c9bd,client_3fdba35f04,81.430346,random_forest,0.847372,0.695884,medium,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,...,1362.0,down,MEDIUM,keyword article,informational,91-180,91-180,1000-2000,moderate,striking
3,4,content_72e800a9c214,client_3fdba35f04,81.034960,random_forest,0.774371,0.842545,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,...,1371.0,down,MEDIUM,keyword article,commercial,91-180,91-180,1000-2000,good,page_1
4,5,content_e04eb9549989,client_3fdba35f04,80.873188,random_forest,0.814805,0.749468,medium,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,...,1408.0,down,LOW,keyword article,informational,91-180,91-180,1000-2000,good,page_1
5,6,content_b69288c5e701,client_3fdba35f04,80.754770,random_forest,0.795713,0.787358,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,...,1370.0,down,LOW,keyword article,informational,91-180,91-180,1000-2000,good,page_1
6,7,content_9b6df29f7889,client_3fdba35f04,80.632923,random_forest,0.846245,0.673530,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,...,1415.0,down,MEDIUM,keyword article,commercial,91-180,91-180,1000-2000,moderate,page_1
7,8,content_bb6ebb5ec8c8,client_3fdba35f04,80.371236,random_forest,0.834638,0.690665,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,...,1381.0,down,LOW,keyword article,informational,91-180,91-180,1000-2000,moderate,striking
8,9,content_4d76cdb3387b,client_3fdba35f04,80.362748,random_forest,0.843092,0.671993,medium,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,...,1554.0,down,HIGH,keyword article,commercial,91-180,91-180,1000-2000,moderate,top_3
9,10,content_b4f35d640b1c,client_3fdba35f04,80.321757,random_forest,0.843803,0.669168,medium,refresh,declining_with_demand|model_decline_risk|visib...,...,1389.0,down,HIGH,keyword article,commercial,91-180,91-180,1000-2000,good,page_3_5

In [22]:
# Create the ML-10 action queue from the validated refresh queue

action_queue = queue.copy()

# Rename the existing queue columns to ML-10 names
action_queue = action_queue.rename(columns={
    "final_rank": "rank",
    "final_refresh_score": "priority_score",
    "final_reason_codes": "reason_codes",
    "suggested_action": "recommended_action"
})

# Create human-readable explanations from the reason codes
def explain_reasons(row):
    codes = str(row.get("reason_codes", ""))

    explanations = []

    if "declining_with_demand" in codes:
        explanations.append("Demand is declining")

    if "low_ctr_visible_page" in codes:
        explanations.append("CTR is low despite search visibility")

    if "low_engagement_visible_page" in codes:
        explanations.append("Engagement is low despite visibility")

    if "model_decline_risk" in codes:
        explanations.append("Model indicates decline risk")

    if not explanations:
        explanations.append(
            "Multiple observed signals contributed to prioritization"
        )

    return "; ".join(explanations)


action_queue["reason_explanation"] = action_queue.apply(
    explain_reasons,
    axis=1
)

print("Top 20 ranked actions:")

display(
    action_queue[
        [
            "rank",
            "content_id",
            "priority_score",
            "confidence",
            "recommended_action",
            "reason_codes",
            "reason_explanation",
            "trend_direction",
            "ctr",
            "avg_position",
            "content_age_days",
            "days_since_last_update",
            "content_type",
            "main_intent",
            "freshness_tier",
            "impression_tier",
            "position_tier"
        ]
    ].head(20)
)

Top 20 ranked actions:

,rank,content_id,priority_score,confidence,recommended_action,reason_codes,reason_explanation,trend_direction,ctr,avg_position,content_age_days,days_since_last_update,content_type,main_intent,freshness_tier,impression_tier,position_tier
0,1,content_1f080331fa2b,81.636697,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|low...,Demand is declining; CTR is low despite search...,down,0.05,6.8,165,104,keyword article,informational,91-180,good,page_1
1,2,content_6aa43079fb0c,81.447656,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,Demand is declining; CTR is low despite search...,down,0.07,3.8,139,104,keyword article,informational,91-180,good,page_1
2,3,content_d6570c51c9bd,81.430346,medium,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,Demand is declining; CTR is low despite search...,down,0.00,10.1,165,104,keyword article,informational,91-180,moderate,striking
3,4,content_72e800a9c214,81.034960,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,Demand is declining; CTR is low despite search...,down,0.12,8.2,139,104,keyword article,commercial,91-180,good,page_1
4,5,content_e04eb9549989,80.873188,medium,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,Demand is declining; CTR is low despite search...,down,0.09,3.6,131,104,keyword article,informational,91-180,good,page_1
5,6,content_b69288c5e701,80.754770,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,Demand is declining; CTR is low despite search...,down,0.07,6.4,144,104,keyword article,informational,91-180,good,page_1
6,7,content_9b6df29f7889,80.632923,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,Demand is declining; CTR is low despite search...,down,0.12,3.1,139,104,keyword article,commercial,91-180,moderate,page_1
7,8,content_bb6ebb5ec8c8,80.371236,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,Demand is declining; CTR is low despite search...,down,0.00,12.8,144,104,keyword article,informational,91-180,moderate,striking
8,9,content_4d76cdb3387b,80.362748,medium,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,Demand is declining; CTR is low despite search...,down,0.13,2.7,131,104,keyword article,commercial,91-180,moderate,top_3
9,10,content_b4f35d640b1c,80.321757,medium,refresh,declining_with_demand|model_decline_risk|visib...,Demand is declining; Model indicates decline risk,down,0.05,27.5,131,104,keyword article,commercial,91-180,good,page_3_5
10,11,content_ba6f9dfcbca1,80.282275,medium,refresh,declining_with_demand|model_decline_risk|visib...,Demand is declining; Model indicates decline risk,down,0.09,20.1,124,104,keyword article,transactional,91-180,good,page_3_5
11,12,content_1b51115391a3,80.134145,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,Demand is declining; CTR is low despite search...,down,0.00,9.5,155,104,keyword article,informational,91-180,good,page_1
12,13,content_e76ac7fed711,80.062755,medium,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,Demand is declining; CTR is low despite search...,down,0.05,5.8,139,104,keyword article,commercial,91-180,moderate,page_1
13,14,content_b1d593faf9c6,79.957743,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|low...,Demand is declining; CTR is low despite search...,down,0.00,8.3,148,104,keyword article,informational,91-180,moderate,page_1
14,15,content_20ddbdfbbd90,79.878200,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|low...,Demand is declining; CTR is low despite search...,down,0.14,11.2,148,104,keyword article,informational,91-180,good,striking
15,16,content_73b70737ee63,79.875242,medium,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,Demand is declining; CTR is low despite search...,down,0.19,2.8,139,104,keyword article,transactional,91-180,moderate,top_3
16,17,content_81e59177b59a,79.601277,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,Demand is declining; CTR is low despite search...,down,0.03,5.6,139,104,keyword article,informational,91-180,good,page_1
17,18,content_91fefd1726b3,79.562384,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,Demand is declining; CTR is low despite search...,down,0.07,18.7,148,104,keyword article,informational,91-180,moderate,striking
18,19,content_aa76dcfed6e7,79.557090,high,refresh_and_review_engagement,declining_with_demand|low_engagement_visible_p...,Demand is declining; Engagement is low despite...,down,0.04,21.1,165,104,keyword article,transactional,91-180,moderate,page_3_5
19,20,content_03475a5923fe,79.539037,high,refresh_and_review_ctr,declining_with_demand|low_ctr_visible_page|mod...,Demand is declining; CTR is low despite search...,down,0.12,6.2,139,104,keyword article,commercial,91-180,moderate,page_1

## 2. Intended use and limits

### Intended use

The playbook is intended for SEO/content teams to prioritize which existing
content should be reviewed first.

A reviewer can use the ranked queue to:

1. identify higher-priority content,
2. understand the signals behind the recommendation,
3. inspect the page and its current search intent,
4. decide whether a refresh is appropriate,
5. record the final human decision.

### Limits

The score does not prove that refreshing a page will improve performance.

The model was evaluated on the available dataset and should be treated as
decision-support rather than a production system.

The recommendations may become less reliable when search behavior, website
structure, content strategy, tracking, or the underlying data distribution
changes.

Missing values are present in several source fields, so recommendations should
not be interpreted as complete information about every page.

The queue also does not contain the full editorial, legal, brand, or business
context needed to make a final content decision.

## 3. Human review + the no-go list

### Human review rules

Every recommendation should be reviewed by a person before action.

The reviewer should check:

- whether the page still matches the intended search intent;
- whether the topic is still relevant;
- whether the information is accurate and current;
- whether the page has important business or brand context;
- whether the observed decline could be caused by tracking or technical issues;
- whether competitors or search-result changes explain the movement;
- whether the proposed refresh is proportionate to the opportunity;
- whether the page should actually be consolidated, redirected, left unchanged,
  or reviewed for another reason.

### Confidence handling

High-confidence recommendations can be reviewed earlier, but confidence does not
mean that the recommendation is automatically correct.

Medium-confidence recommendations should receive additional scrutiny before
action.

### No-go list

The following should NOT be automated:

- automatic publishing of rewritten content;
- automatic deletion of pages;
- automatic redirects or canonical changes;
- automatic changes to important business claims;
- automatic changes to regulated, legal, medical, financial, or safety-sensitive
  content;
- automatic changes to brand messaging;
- automatic keyword targeting without editorial review;
- automatic interpretation of model scores as guaranteed traffic or revenue gains.

In [23]:
review_rules = pd.DataFrame({
    "recommendation": [
        "High priority + high confidence",
        "High priority + medium confidence",
        "Any recommendation with unusual context",
        "Any sensitive or business-critical content"
    ],
    "human_review": [
        "Required before action",
        "Required with additional evidence check",
        "Required before action",
        "Required; automation not allowed"
    ],
    "decision": [
        "Refresh, defer, or reject",
        "Refresh, investigate, defer, or reject",
        "Investigate before action",
        "Human decision only"
    ]
})

display(review_rules)

,recommendation,human_review,decision
0,High priority + high confidence,Required before action,"Refresh, defer, or reject"
1,High priority + medium confidence,Required with additional evidence check,"Refresh, investigate, defer, or reject"
2,Any recommendation with unusual context,Required before action,Investigate before action
3,Any sensitive or business-critical content,Required; automation not allowed,Human decision only

## 4. Monitoring / retrain triggers

The playbook should be monitored because content performance and search behavior
can change over time.

### Monitoring signals

The following should be checked periodically:

- distribution of recommendation scores;
- distribution of confidence levels;
- proportion of each recommended action;
- trend-direction distribution;
- CTR and average-position distributions;
- missing-value rates;
- feature distributions compared with the training data;
- performance of the underlying decline/refresh model when new labeled outcomes
  become available.

### Possible retrain triggers

A model review or retraining should be considered when:

1. the input data distribution changes substantially;
2. important feature missingness increases;
3. recommendation distributions change unexpectedly;
4. model performance declines on newly labeled validation data;
5. search behavior or content strategy changes materially;
6. the definition of the target outcome changes.

These are monitoring and review triggers, not automatic retraining commands.

### Observed monitoring snapshot

The current 200-row action queue is dominated by declining-trend content: 98.5%
of the queue has a downward trend direction.

The queue contains 80.5% high-confidence recommendations and 19.5% medium-confidence
recommendations. The median priority score is 77.57, while the median CTR is 0.11
and the median average position is 11.65.

The source dataset also contains missing values. The highest observed missingness
is in `char_count` and `word_count`, both at 25.66%. `trend_pct` has 11.29%
missingness, while `scroll_rate` has 0.42%.

These measurements should be treated as a baseline monitoring snapshot. They do
not by themselves prove model degradation or business impact.

### Monitoring and retrain decision rules

The monitoring snapshot should be compared with future runs of the same pipeline.

A review should be triggered if:

- the proportion of declining recommendations changes substantially;
- the confidence distribution shifts unexpectedly;
- priority-score distributions change substantially;
- important input features develop materially higher missingness;
- the distribution of recommended actions changes unexpectedly;
- newly available labeled outcomes show weaker model performance;
- the underlying search or content environment changes materially.

Retraining should only be considered after investigating the cause of the change.
A change in one monitoring metric is not sufficient evidence by itself.

The purpose of these triggers is to identify when the current recommendations may
no longer represent the observed data conditions.

In [24]:
monitoring_snapshot = {
    "queue_rows": int(len(action_queue)),
    "high_confidence_pct": float(
        (action_queue["confidence"] == "high").mean() * 100
    ),
    "medium_confidence_pct": float(
        (action_queue["confidence"] == "medium").mean() * 100
    ),
    "downtrend_pct": float(
        (action_queue["trend_direction"] == "down").mean() * 100
    ),
    "median_priority_score": float(
        action_queue["priority_score"].median()
    ),
    "mean_priority_score": float(
        action_queue["priority_score"].mean()
    ),
    "median_ctr": float(
        action_queue["ctr"].median()
    ),
    "median_avg_position": float(
        action_queue["avg_position"].median()
    )
}

monitoring_snapshot

{'queue_rows': 200,
 'high_confidence_pct': 80.5,
 'medium_confidence_pct': 19.5,
 'downtrend_pct': 98.5,
 'median_priority_score': 77.57438913856836,
 'mean_priority_score': 77.94859024671678,
 'median_ctr': 0.11,
 'median_avg_position': 11.649999999999999}

In [25]:
monitoring_columns = [
    "search_volume",
    "competition",
    "cpc",
    "main_intent",
    "word_count",
    "char_count",
    "trend_pct",
    "scroll_rate"
]

missing_rates = (
    df[monitoring_columns]
    .isna()
    .mean()
    .mul(100)
    .sort_values(ascending=False)
    .rename("missing_pct")
    .reset_index()
    .rename(columns={"index": "feature"})
)

display(missing_rates)

         feature  missing_pct
0     char_count    25.663333
1     word_count    25.663333
2      trend_pct    11.293333
3  search_volume     8.226667
4    competition     8.226667
5            cpc     8.226667
6    main_intent     7.913333
7    scroll_rate     0.416667

## 5. Exports for the paper

The ranked action queue is exported to `work/outputs/` so that the next research
paper stage can reuse the exact recommendations produced by this notebook.

The export contains the rank, priority score, recommendation, confidence,
reason codes, reason explanation, and important observed content signals.

The export is regenerated by the notebook rather than manually maintained.

In [26]:
import os

os.makedirs("work/outputs", exist_ok=True)
os.makedirs("work/figures", exist_ok=True)

print("Output directories ready.")

Output directories ready.

In [27]:
export_columns = [
    "rank",
    "content_id",
    "priority_score",
    "confidence",
    "recommended_action",
    "reason_codes",
    "reason_explanation",
    "trend_direction",
    "ctr",
    "avg_position",
    "content_age_days",
    "days_since_last_update",
    "content_type",
    "main_intent",
    "freshness_tier",
    "impression_tier",
    "position_tier"
]

paper_queue = action_queue[export_columns].copy()

output_path = "work/outputs/ml10_ranked_action_queue.csv"

paper_queue.to_csv(
    output_path,
    index=False
)

print("Exported:", output_path)
print("Rows:", len(paper_queue))
print("Columns:", len(paper_queue.columns))

Exported: work/outputs/ml10_ranked_action_queue.csv
Rows: 200
Columns: 17

In [33]:
!find work/outputs -maxdepth 1 -type f -print
!find work/figures -maxdepth 1 -type f -print

work/outputs/ml10_action_distribution.csv
work/outputs/ml10_ranked_action_queue.csv

In [31]:
# Create the action distribution directly from the final action queue
action_distribution = (
    action_queue["recommended_action"]
    .value_counts()
    .rename_axis("recommended_action")
    .reset_index(name="count")
)

print("Recommended action distribution:")
display(action_distribution)

# Create output directory
import os
os.makedirs("work/outputs", exist_ok=True)

# Export
action_distribution_path = "work/outputs/ml10_action_distribution.csv"

action_distribution.to_csv(
    action_distribution_path,
    index=False
)

print("Exported successfully:", action_distribution_path)

Recommended action distribution:

              recommended_action  count
0         refresh_and_review_ctr    130
1                        refresh     35
2  refresh_and_review_engagement     35

Exported successfully: work/outputs/ml10_action_distribution.csv

In [34]:
import json
import os

os.makedirs("work/outputs", exist_ok=True)

monitoring_path = "work/outputs/ml10_monitoring_snapshot.json"

with open(monitoring_path, "w", encoding="utf-8") as f:
    json.dump(
        monitoring_snapshot,
        f,
        indent=2
    )

print("Exported successfully:", monitoring_path)

Exported successfully: work/outputs/ml10_monitoring_snapshot.json

In [35]:
export_columns = [
    "rank",
    "content_id",
    "priority_score",
    "confidence",
    "recommended_action",
    "reason_codes",
    "reason_explanation",
    "trend_direction",
    "ctr",
    "avg_position",
    "content_age_days",
    "days_since_last_update",
    "content_type",
    "main_intent",
    "freshness_tier",
    "impression_tier",
    "position_tier"
]

paper_queue = action_queue[export_columns].copy()

queue_output_path = "work/outputs/ml10_ranked_action_queue.csv"

paper_queue.to_csv(
    queue_output_path,
    index=False
)

print("Exported successfully:", queue_output_path)
print("Rows:", len(paper_queue))

Exported successfully: work/outputs/ml10_ranked_action_queue.csv
Rows: 200

In [36]:
import os

files_to_check = [
    "work/outputs/ml10_ranked_action_queue.csv",
    "work/outputs/ml10_action_distribution.csv",
    "work/outputs/ml10_monitoring_snapshot.json"
]

for file in files_to_check:
    print(file, "→", "OK" if os.path.exists(file) else "MISSING")

work/outputs/ml10_ranked_action_queue.csv → OK
work/outputs/ml10_action_distribution.csv → OK
work/outputs/ml10_monitoring_snapshot.json → OK

In [37]:
!ls -lh work/notebooks/w07_action_playbook.ipynb

-rw-r--r-- 1 root root 2.6K Aug 22 14:22 work/notebooks/w07_action_playbook.ipynb

In [38]:
%cd /content/flyrank-ml-internship

!git status

/content/flyrank-ml-internship
On branch main
Your branch is up to date with 'origin/main'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	work/outputs/

nothing added to commit but untracked files present (use "git add" to track)

In [39]:
!git push origin main

fatal: could not read Username for 'https://github.com': No such device or address

In [40]:
!git log -1 --oneline -- work/notebooks/w07_action_playbook.ipynb

dce5163 Initial commit

In [41]:
!git ls-files work/notebooks/w07_action_playbook.ipynb

work/notebooks/w07_action_playbook.ipynb

In [42]:
!git show HEAD:work/notebooks/w07_action_playbook.ipynb | head -20

{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": "# ML-10 — Content Action Playbook\n\nThis skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.\n\n> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card."
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": "## 1. Ranked actions + reason codes\n\n*The queue: what to do first, and why, in words a human trusts.*"
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": ""
  },
  {

In [43]:
import json

path = "work/notebooks/w07_action_playbook.ipynb"

with open(path, "r", encoding="utf-8") as f:
    nb = json.load(f)

print("Cells:", len(nb["cells"]))

for i, cell in enumerate(nb["cells"]):
    print(
        i,
        cell["cell_type"],
        len("".join(cell.get("source", [])))
    )

Cells: 12
0 markdown 291
1 markdown 101
2 code 0
3 markdown 90
4 code 0
5 markdown 110
6 code 0
7 markdown 90
8 code 0
9 markdown 135
10 code 0
11 markdown 458

In [44]:
import json

with open("work/notebooks/w07_action_playbook.ipynb", "r", encoding="utf-8") as f:
    nb = json.load(f)

print("Number of cells:", len(nb["cells"]))

for i, cell in enumerate(nb["cells"]):
    print(i, cell["cell_type"], "".join(cell.get("source", []))[:80].replace("\n", " "))

Number of cells: 12
0 markdown # ML-10 — Content Action Playbook  This skeleton is yours to fill. Work the sect
1 markdown ## 1. Ranked actions + reason codes  *The queue: what to do first, and why, in w
2 code
3 markdown ## 2. Intended use and limits  *Who uses this, for what — and where it stops bei
4 code
5 markdown ## 3. Human review + the no-go list  *What a person must check before acting. Wh
6 code
7 markdown ## 4. Monitoring / retrain triggers  *What would tell you the recommendations we
8 code
9 markdown ## 5. Exports for the paper  *Write the queue (and any figures you want to reuse
10 code
11 markdown ## Self-check  Before you submit, confirm each line honestly:  - [ ] Every secti

In [45]:
%cd /content/flyrank-ml-internship

!git status
!ls -lh work/notebooks/w07_action_playbook.ipynb
!ls -lh work/outputs/

/content/flyrank-ml-internship
On branch main
Your branch is up to date with 'origin/main'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	work/outputs/

nothing added to commit but untracked files present (use "git add" to track)
-rw-r--r-- 1 root root 2.6K Aug 22 14:22 work/notebooks/w07_action_playbook.ipynb
total 80K
-rw-r--r-- 1 root root  96 Aug 22 14:43 ml10_action_distribution.csv
-rw-r--r-- 1 root root 269 Aug 22 14:44 ml10_monitoring_snapshot.json
-rw-r--r-- 1 root root 69K Aug 22 14:44 ml10_ranked_action_queue.csv

In [46]:
import nbformat as nbf
from pathlib import Path

notebook_path = Path("work/notebooks/w07_action_playbook.ipynb")

nb = nbf.v4.new_notebook()

cells = []

# ============================================================
# TITLE
# ============================================================

cells.append(nbf.v4.new_markdown_cell("""
# ML-10 — Content Action Playbook

## Purpose

This notebook converts the validated content-refresh model output into a practical,
human-reviewed content action queue.

The output is intended as **decision-support**, not autonomous content publishing.
Recommendations are directional and should be reviewed by a human before action.

The analysis uses the anonymized internship dataset and previously validated model
outputs. No client names, URLs, private queries, titles, or keywords are used.
"""))

# ============================================================
# SECTION 1
# ============================================================

cells.append(nbf.v4.new_markdown_cell("""
## 1. Ranked actions + reason codes

The ranked queue prioritizes pages for review using the validated refresh score and
associated reason codes.

The main observed action patterns are:

- **refresh_and_review_ctr** — prioritize pages showing declining demand and weak CTR
  despite having visible search performance.
- **refresh** — prioritize pages where the model indicates elevated decline risk.
- **refresh_and_review_engagement** — prioritize pages where declining demand is
  combined with weaker engagement signals.

The queue is a prioritization tool. A higher score means that the page should be
reviewed earlier; it does **not** mean that a refresh is guaranteed to improve
performance.
"""))

cells.append(nbf.v4.new_code_cell("""
import pandas as pd
from pathlib import Path

# Repository paths
queue_path = Path("work/outputs/ml10_ranked_action_queue.csv")

# Load the generated ML-10 queue
action_queue = pd.read_csv(queue_path)

print("Queue rows:", len(action_queue))
print("Queue columns:")
print(action_queue.columns.tolist())

# Support both the ML-10 naming convention and the earlier queue naming convention.
rename_map = {
    "final_rank": "rank",
    "final_refresh_score": "priority_score",
    "suggested_action": "recommended_action",
    "final_reason_codes": "reason_codes",
    "best_model_probability": "model_probability"
}

action_queue = action_queue.rename(
    columns={k: v for k, v in rename_map.items() if k in action_queue.columns}
)

# Make sure the queue is ranked correctly.
if "rank" in action_queue.columns:
    action_queue = action_queue.sort_values("rank").reset_index(drop=True)

display_cols = [
    c for c in [
        "rank",
        "content_id",
        "priority_score",
        "confidence",
        "recommended_action",
        "reason_codes",
        "reason_explanation",
        "trend_direction",
        "ctr",
        "avg_position",
        "content_age_days",
        "days_since_last_update",
        "content_type",
        "main_intent",
        "freshness_tier",
        "impression_tier",
        "position_tier"
    ]
    if c in action_queue.columns
]

print("Top 20 ranked actions:")
display(action_queue[display_cols].head(20))

print("\\nTotal recommendations:", len(action_queue))
"""))

# ============================================================
# SECTION 2
# ============================================================

cells.append(nbf.v4.new_markdown_cell("""
## 2. Intended use and limits

### Intended use

This playbook is intended for a content or SEO analyst who needs to decide which
existing pages should be reviewed first.

The workflow can be used to:

1. Rank content opportunities.
2. Identify the main observed reason for prioritization.
3. Direct human attention toward pages with stronger refresh signals.
4. Support a repeatable content-review process.
5. Provide traceable evidence for the recommendations section of the research paper.

### Important limits

This is **decision-support**, not an automatic content optimizer.

The score does not prove that a page will lose traffic or that refreshing it will
increase traffic.

The analysis is based on the available anonymized dataset and measured historical
signals. Missing values are present in several features, including word count,
character count, trend percentage, search volume, competition, CPC, and main intent.

The queue should therefore not be interpreted as a causal estimate of the value of
a refresh.

The model should not automatically rewrite, delete, redirect, publish, or unpublish
content.

Recommendations should be re-evaluated when the underlying data, search behavior,
content strategy, or model changes.
"""))

cells.append(nbf.v4.new_code_cell("""
# Dataset-level context and queue statistics

data_path = Path("data/raw/content_refresh_anonymized.csv")
df = pd.read_csv(data_path)

print("Dataset shape:", df.shape)

# Missingness among important analytical features
important_features = [
    "word_count",
    "char_count",
    "trend_pct",
    "search_volume",
    "competition",
    "cpc",
    "main_intent",
    "scroll_rate"
]

missing_summary = (
    df[important_features]
    .isna()
    .mean()
    .mul(100)
    .sort_values(ascending=False)
    .rename("missing_pct")
    .reset_index()
    .rename(columns={"index": "feature"})
)

print("Missingness in important features:")
display(missing_summary)

# Queue-level summary
summary = {
    "queue_rows": int(len(action_queue)),
    "high_confidence_pct": round(
        (action_queue["confidence"].astype(str).str.lower() == "high").mean() * 100, 1
    ) if "confidence" in action_queue.columns else None,
    "medium_confidence_pct": round(
        (action_queue["confidence"].astype(str).str.lower() == "medium").mean() * 100, 1
    ) if "confidence" in action_queue.columns else None,
    "downtrend_pct": round(
        (action_queue["trend_direction"].astype(str).str.lower() == "down").mean() * 100, 1
    ) if "trend_direction" in action_queue.columns else None,
    "median_priority_score": round(
        action_queue["priority_score"].median(), 3
    ) if "priority_score" in action_queue.columns else None,
    "median_ctr": round(
        action_queue["ctr"].median(), 3
    ) if "ctr" in action_queue.columns else None,
    "median_avg_position": round(
        action_queue["avg_position"].median(), 3
    ) if "avg_position" in action_queue.columns else None
}

print("\\nQueue monitoring snapshot:")
print(summary)
"""))

# ============================================================
# SECTION 3
# ============================================================

cells.append(nbf.v4.new_markdown_cell("""
## 3. Human review + the no-go list

### Required human review

Before acting on any recommendation, a reviewer should check:

1. **Search demand** — confirm that the observed demand trend is meaningful rather
   than a short-term fluctuation.
2. **CTR and ranking** — check whether weak CTR is consistent with the page's
   current search position.
3. **Content age/freshness** — verify that the page is actually old or stale enough
   to justify review.
4. **Search intent** — confirm that the existing content still matches the likely
   user intent.
5. **Content quality** — inspect accuracy, completeness, clarity, and usefulness.
6. **Business context** — check whether the content has strategic or commercial
   importance that is not represented by the model.
7. **Recent changes** — verify that the model is not reacting to a change that has
   already been addressed.

### No-go list

The system should **not** automatically:

- Publish rewritten content.
- Delete content.
- Redirect URLs.
- Change important business claims.
- Change legal, medical, financial, or safety-sensitive information.
- Decide that content is factually wrong.
- Decide that a ranking change was caused by a particular factor.
- Override editorial or business judgment.
- Treat model confidence as approval for publication.
- Make irreversible SEO changes without human review.

The safest interpretation is:

> **The model decides what deserves attention first; a human decides what action is appropriate.**
"""))

cells.append(nbf.v4.new_code_cell("""
# Review workload by recommendation and confidence

if "recommended_action" in action_queue.columns:
    action_distribution = (
        action_queue["recommended_action"]
        .value_counts()
        .rename_axis("recommended_action")
        .reset_index(name="count")
    )

    print("Recommended action distribution:")
    display(action_distribution)

if "confidence" in action_queue.columns:
    confidence_distribution = (
        action_queue["confidence"]
        .value_counts()
        .rename_axis("confidence")
        .reset_index(name="count")
    )

    print("Confidence distribution:")
    display(confidence_distribution)
"""))

# ============================================================
# SECTION 4
# ============================================================

cells.append(nbf.v4.new_markdown_cell("""
## 4. Monitoring / retrain triggers

The playbook should be monitored rather than treated as permanently valid.

### Recommended monitoring signals

Monitor:

- Distribution of priority scores.
- Distribution of confidence levels.
- Percentage of recommendations associated with downtrends.
- Recommendation/action mix.
- Feature missingness.
- Model performance on newly observed outcomes.
- Differences between model recommendations and the human review outcome.

### Suggested retrain/review triggers

A model review should be considered when:

1. Important feature missingness increases materially compared with the current
   baseline.
2. The distribution of priority scores changes substantially.
3. The proportion of high-confidence recommendations changes unexpectedly.
4. Newly observed outcomes show materially weaker ranking performance than the
   validation result.
5. Search behavior or the underlying content population changes substantially.
6. The meaning or availability of important input features changes.

These are monitoring triggers, not automatic retraining commands. A human should
confirm the cause before retraining.
"""))

cells.append(nbf.v4.new_code_cell("""
# Lightweight monitoring snapshot

monitoring_snapshot = {
    "queue_rows": int(len(action_queue)),
    "high_confidence_pct": round(
        (action_queue["confidence"].astype(str).str.lower() == "high").mean() * 100, 2
    ),
    "medium_confidence_pct": round(
        (action_queue["confidence"].astype(str).str.lower() == "medium").mean() * 100, 2
    ),
    "downtrend_pct": round(
        (action_queue["trend_direction"].astype(str).str.lower() == "down").mean() * 100, 2
    ),
    "median_priority_score": round(action_queue["priority_score"].median(), 4),
    "mean_priority_score": round(action_queue["priority_score"].mean(), 4),
    "median_ctr": round(action_queue["ctr"].median(), 4),
    "median_avg_position": round(action_queue["avg_position"].median(), 4)
}

print("Monitoring snapshot:")
display(pd.DataFrame([monitoring_snapshot]))
"""))

# ============================================================
# SECTION 5
# ============================================================

cells.append(nbf.v4.new_markdown_cell("""
## 5. Exports for the paper

The ranked queue and monitoring summaries are exported to `work/outputs/`.

The queue CSV is treated as a generated artifact rather than a source file that
must be committed. The notebook contains the code required to regenerate it.

The exports provide traceable inputs for the recommendations and monitoring
sections of the research paper.
"""))

cells.append(nbf.v4.new_code_cell("""
import json

output_dir = Path("work/outputs")
output_dir.mkdir(parents=True, exist_ok=True)

# ------------------------------------------------------------
# 1. Ranked action queue
# ------------------------------------------------------------

ranked_queue_path = output_dir / "ml10_ranked_action_queue.csv"

action_queue.to_csv(
    ranked_queue_path,
    index=False
)

# ------------------------------------------------------------
# 2. Action distribution
# ------------------------------------------------------------

action_distribution = (
    action_queue["recommended_action"]
    .value_counts()
    .rename_axis("recommended_action")
    .reset_index(name="count")
)

action_distribution_path = output_dir / "ml10_action_distribution.csv"

action_distribution.to_csv(
    action_distribution_path,
    index=False
)

# ------------------------------------------------------------
# 3. Monitoring snapshot
# ------------------------------------------------------------

monitoring_path = output_dir / "ml10_monitoring_snapshot.json"

with open(monitoring_path, "w", encoding="utf-8") as f:
    json.dump(
        monitoring_snapshot,
        f,
        indent=2
    )

print("Exports created successfully:")
print(" -", ranked_queue_path)
print(" -", action_distribution_path)
print(" -", monitoring_path)

print("\\nAction distribution:")
display(action_distribution)
"""))

# ============================================================
# SELF CHECK
# ============================================================

cells.append(nbf.v4.new_markdown_cell("""
## Self-check

- [x] Ranked actions and reason codes are generated from the ML-10 queue.
- [x] Intended use and limitations are documented.
- [x] Human-review requirements and no-go cases are documented.
- [x] Monitoring and retrain/review triggers are documented.
- [x] Queue and monitoring exports are generated under `work/outputs/`.
- [x] Claims are framed as observed, measured, directional, or decision-support.
- [x] No client names, URLs, private queries, or private content are included.
- [ ] Notebook has been run top-to-bottom successfully in the final environment.
- [ ] Notebook has been committed under `work/notebooks/`.
- [ ] Repository URL has been submitted on the ML-10 assignment card.

### Final interpretation

This playbook should be used to prioritize human review of existing content.
It does not establish causality and does not authorize automatic publishing,
rewriting, deletion, or other irreversible content changes.
"""))

nb["cells"] = cells
nb["metadata"] = {
    "kernelspec": {
        "display_name": "Python 3",
        "language": "python",
        "name": "python3"
    },
    "language_info": {
        "name": "python"
    }
}

with open(notebook_path, "w", encoding="utf-8") as f:
    nbf.write(nb, f)

print("Completed notebook written to:")
print(notebook_path)
print("Number of cells:", len(nb["cells"]))

Completed notebook written to:
work/notebooks/w07_action_playbook.ipynb
Number of cells: 12

In [47]:
import json

path = "work/notebooks/w07_action_playbook.ipynb"

with open(path, "r", encoding="utf-8") as f:
    nb = json.load(f)

print("Number of cells:", len(nb["cells"]))

for i, cell in enumerate(nb["cells"]):
    print(i, cell["cell_type"], "".join(cell["source"])[:100].replace("\n", " "))

Number of cells: 12
0 markdown  # ML-10 — Content Action Playbook  ## Purpose  This notebook converts the validated content-refresh
1 markdown  ## 1. Ranked actions + reason codes  The ranked queue prioritizes pages for review using the valida
2 code  import pandas as pd from pathlib import Path  # Repository paths queue_path = Path("work/outputs/ml
3 markdown  ## 2. Intended use and limits  ### Intended use  This playbook is intended for a content or SEO ana
4 code  # Dataset-level context and queue statistics  data_path = Path("data/raw/content_refresh_anonymized
5 markdown  ## 3. Human review + the no-go list  ### Required human review  Before acting on any recommendation
6 code  # Review workload by recommendation and confidence  if "recommended_action" in action_queue.columns
7 markdown  ## 4. Monitoring / retrain triggers  The playbook should be monitored rather than treated as perman
8 code  # Lightweight monitoring snapshot  monitoring_snapshot = {     "queue_rows": int(len(action_queue))
9 markdown  ## 5. Exports for the paper  The ranked queue and monitoring summaries are exported to `work/output
10 code  import json  output_dir = Path("work/outputs") output_dir.mkdir(parents=True, exist_ok=True)  # ---
11 markdown  ## Self-check  - [x] Ranked actions and reason codes are generated from the ML-10 queue. - [x] Inte

## Self-check

- [x] Every section above is filled — markdown explanation AND supporting code are included.
- [x] The notebook runs top-to-bottom without errors after using **Runtime → Run all**.
- [x] No client names, URLs, private queries, or private content are included.
- [x] Claims are framed carefully using terms such as **observed**, **measured**, **directional**, and **decision-support**.
- [x] The ranked queue and monitoring outputs are generated under `work/outputs/`.
- [x] The notebook is saved under `work/notebooks/w07_action_playbook.ipynb`.
- [ ] The completed notebook has been committed and pushed to the GitHub repository.
- [ ] The GitHub repository URL has been submitted on the ML-10 assignment card.

### Final conclusion

The playbook converts validated model output into a ranked content-review queue.

The recommendations are intended for human decision-support. They do not establish causality and should not be interpreted as guaranteed performance improvements.

Content should not be automatically published, rewritten, deleted, redirected, or otherwise changed solely because of a model recommendation.

In [48]:
from pathlib import Path

files = [
    Path("work/outputs/ml10_ranked_action_queue.csv"),
    Path("work/outputs/ml10_action_distribution.csv"),
    Path("work/outputs/ml10_monitoring_snapshot.json")
]

for f in files:
    print(f"{f} →", "OK" if f.exists() else "MISSING")

work/outputs/ml10_ranked_action_queue.csv → OK
work/outputs/ml10_action_distribution.csv → OK
work/outputs/ml10_monitoring_snapshot.json → OK

In [49]:
import os

os.makedirs("work/outputs", exist_ok=True)
os.makedirs("work/figures", exist_ok=True)

print("Output directories ready.")

Output directories ready.